spring.application.name: malls-admin
spring.session.redis.namespace: session:${spring.application.name}
spring:
  liquibase:
    change-log: classpath:/db/main.xml
  datasource:
    table:
      prefix: 
    